[package]
name = "github-api-client"
version = "0.0.0"
authors = ["Jamie Winsor <reset@habitat.sh>"]
workspace = "../../"

[dependencies]
base64 = "*"
frank_jwt = { git = "https://github.com/habitat-sh/frank_jwt", branch = "habitat" }
hyper = "*"
hyper-openssl = "*"
log = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"
