[profile.release]
debug = true

[workspace]
members = [
  "components/airlock",
  "components/builder-admin",
  "components/builder-api",
  "components/builder-api-client",
  "components/builder-core",
  "components/builder-db",
  "components/builder-depot",
  "components/builder-depot-client",
  "components/builder-graph",
  "components/builder-http-gateway",
  "components/builder-jobsrv",
  "components/builder-originsrv",
  "components/builder-protocol",
  "components/builder-router",
  "components/builder-sessionsrv",
  "components/builder-worker",
  "components/github-api-client",
  "components/op",
  "components/segment-api-client",
]
