auth_token = "{{cfg.auth_token}}"
auto_publish = {{cfg.auto_publish}}
depot_channel = "{{cfg.depot_channel}}"
data_path = "{{pkg.svc_data_path}}"
{{~#if cfg.depot_url}}
depot_url = "{{cfg.depot_url}}"
{{~else}}
depot_url = "{{bind.depot.first.cfg.url}}/depot"
{{~/if}}

{{~#eachAlive bind.jobsrv.members as |member|}}
[[jobsrv]]
host = "{{member.sys.ip}}"
port = {{member.cfg.worker_port}}
heartbeat = {{member.cfg.worker_heartbeat}}
{{~/eachAlive}}

{{~#eachAlive bind.datastore.members as |member|}}
[datastore]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/eachAlive}}
