auth_token = "{{cfg.auth_token}}"
auto_publish = {{cfg.auto_publish}}
data_path = "{{pkg.svc_data_path}}"
log_path = "{{cfg.svc_var_path}}"
bldr_channel = "{{cfg.bldr_channel}}"
features_enabled = "{{cfg.features_enabled}}"
{{~#eachAlive bind.depot.members as |member|}}
{{~#if @first}}
bldr_url = "{{member.cfg.url}}"
{{~/if}}
{{~/eachAlive}}

[github]
app_private_key = "{{pkg.svc_files_path}}/builder-github-app.pem"
{{toToml cfg.github}}

{{~#eachAlive bind.jobsrv.members as |member|}}
[[jobsrv]]
host = "{{member.sys.ip}}"
port = {{member.cfg.worker_port}}
heartbeat = {{member.cfg.worker_heartbeat}}
log_port = {{member.cfg.log_port}}
{{~/eachAlive}}
