auth_token = "{{cfg.auth_token}}"
auto_publish = {{cfg.auto_publish}}
data_path = "{{pkg.svc_data_path}}"
bldr_channel = "{{cfg.bldr_channel}}"
bldr_url = "{{bind.depot.first.cfg.url}}"

{{~#eachAlive bind.jobsrv.members as |member|}}
[[jobsrv]]
host = "{{member.sys.ip}}"
port = {{member.cfg.worker_port}}
heartbeat = {{member.cfg.worker_heartbeat}}
log_port = {{member.cfg.log_port}}
{{~/eachAlive}}
