{{toToml cfg}}
data_path = "{{pkg.svc_data_path}}"

{{~#eachAlive bind.jobsrv.members as |member|}}
[[jobsrv]]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
heartbeat = {{member.cfg.heartbeat}}
{{~/eachAlive}}

{{~#eachAlive bind.datastore.members as |member|}}
[datastore]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/eachAlive}}
