{{toToml cfg}}
data_path = "{{pkg.svc_data_path}}"
depot_url = "{{bind.depot.first.cfg.url}}"

{{~#eachAlive bind.jobsrv.members as |member|}}
[[jobsrv]]
host = "{{member.sys.ip}}"
port = {{member.cfg.worker_port}}
heartbeat = {{member.cfg.worker_heartbeat}}
{{~/eachAlive}}

{{~#eachAlive bind.datastore.members as |member|}}
[datastore]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/eachAlive}}
