[package]
name = "oauth-common"
version = "0.0.0"
authors = ["Josh Black <raskchanky@gmail.com>"]

[dependencies]
habitat_http_client = { git = "https://github.com/habitat-sh/core.git" }
hyper = "0.10"
serde_json = ">= 1.0"
