key_dir = "{{pkg.svc_files_path}}"

[app]
{{toToml cfg.app}}
routers = [
  {{~#eachAlive bind.router.members as |member|}}
  { host = "{{member.sys.ip}}", port = {{member.cfg.port}} },
  {{~/eachAlive}}
]

[datastore]
{{toToml cfg.datastore}}
{{~#eachAlive bind.datastore.members as |member|}}
{{~#if @first}}
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/if}}
{{~/eachAlive}}

[archive]
local_dir = "{{pkg.svc_data_path}}"
{{toToml cfg.archive}}
