github_admin_team = 0
github_builder_teams = []
github_build_worker_teams = []
shards = []

[datastore]
user = "hab"
password = ""
database = "builder_sessionsrv"
connection_retry_ms = 300
connection_timeout_sec = 3600

[github]
url = "https://api.github.com"
client_id = ""
client_secret = ""
