[package]
name = "github-api-client"
version = "0.0.0"
authors = ["Jamie Winsor <reset@habitat.sh>", "Josh Black <raskchanky@gmail.com>"]
workspace = "../../"

[dependencies]
base64 = "*"
frank_jwt = { git = "https://github.com/habitat-sh/frank_jwt", branch = "habitat" }
habitat_http_client = { git = "https://github.com/habitat-sh/core.git" }
hyper = "0.10"
hyper-openssl = "0.2"
log = "*"
regex = "*"
serde = ">= 1.0"
serde_derive = ">= 1.0"
serde_json = ">= 1.0"
time = "*"

# For metrics library
[dependencies.builder_core]
path = "../builder-core"
