cookie_domain        = ""
demo_app_url         = "https://www.habitat.sh/demo/build-system/steps/1/"
docs_url             = "https://www.habitat.sh/docs"
enable_builder       = false
environment          = "production"
hosted               = false
source_code_url      = "https://github.com/habitat-sh/habitat"
status_url           = "https://status.habitat.sh/"
tutorials_url        = "https://www.habitat.sh/learn"
use_gravatar         = true
www_url              = "https://www.habitat.sh"

[github]
app_id       = 5565
app_url      = "https://github.com/apps/habitat-builder"
url          = "https://api.github.com"

[oauth]
authorize_url  = "https://github.com/login/oauth/authorize"
client_id      = ""
provider       = "github"
redirect_url   = ""
signup_url     = "https://github.com/join"

[nginx]
worker_connections   = 8000
worker_processes     = "auto"
worker_rlimit_nofile = 8192

[http]
keepalive_timeout = "20s"
listen_port       = 80
sendfile          = "on"
tcp_nopush        = "on"
tcp_nodelay       = "on"
