[package]
name = "oauth-client"
version = "0.0.0"
authors = ["Josh Black <raskchanky@gmail.com>"]
description = "OAuth Client"
workspace = "../../"

[dependencies]
log = "*"
reqwest = "*"
serde = ">= 1.0.0"
serde_derive = ">= 1.0.0"
serde_json = ">= 1.0.0"

# For metrics library
[dependencies.builder_core]
path = "../builder-core"
