auth_token = "{{cfg.auth_token}}"
promote_channel = "{{cfg.promote_channel}}"
log_dir = "{{pkg.svc_var_path}}"
{{~#if cfg.depot_url}}
depot_url = "{{cfg.depot_url}}"
{{~else}}
depot_url = "{{bind.depot.first.cfg.url}}/depot"
{{~/if}}

{{~#eachAlive bind.router.members as |member|}}
[[routers]]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
heartbeat = {{member.cfg.heartbeat}}
{{~/eachAlive}}

[datastore]
{{toToml cfg.datastore}}
{{~#eachAlive bind.datastore.members as |member|}}
{{~#if @first}}
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/if}}
{{~/eachAlive}}
