shards = [
  0
]

{{~#eachAlive bind.router.members as |member|}}
[[router]]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
heartbeat = {{member.cfg.heartbeat}}
{{~/eachAlive}}

[datastore]
{{toToml cfg.datastore}}
{{~#eachAlive bind.datastore.members as |member|}}
{{~#if @first}}
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/if}}
{{~/eachAlive}}
