log_level = "info"
auth_token = ""
auto_publish = true
bldr_channel = "unstable"
features_enabled = ""

[github]
url = "https://api.github.com"
web_url = "https://github.com"
client_id = ""
client_secret = ""
app_id = 5565
