shards = {{toToml cfg.shards}}

[permissions]
{{toToml cfg.permissions}}

[github]
app_private_key = "{{pkg.svc_files_path}}/builder-github-app.pem"
{{toToml cfg.github}}

{{~#eachAlive bind.router.members as |member|}}
[[routers]]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/eachAlive}}

[datastore]
{{toToml cfg.datastore}}
{{~#eachAlive bind.datastore.members as |member|}}
{{~#if @first}}
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/if}}
{{~/eachAlive}}
