github_admin_team = {{cfg.github_admin_team}}
github_builder_teams = {{cfg.github_builder_teams}}
github_build_worker_teams = {{cfg.github_build_worker_teams}}
shards = {{toToml cfg.shards}}

[github]
{{toToml cfg.github}}

{{~#eachAlive bind.router.members as |member|}}
[[routers]]
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
heartbeat = {{member.cfg.heartbeat}}
{{~/eachAlive}}

[datastore]
{{toToml cfg.datastore}}
{{~#eachAlive bind.datastore.members as |member|}}
{{~#if @first}}
host = "{{member.sys.ip}}"
port = {{member.cfg.port}}
{{~/if}}
{{~/eachAlive}}
